// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PropertyWeb.Data;

#nullable disable

namespace PropertyWeb.Migrations
{
    [DbContext(typeof(Application_context))]
    [Migration("20251120113031_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PropertyWeb.Models.Payment_record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("amount");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<Guid>("Owner_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("Property_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("property_id");

                    b.Property<DateTime>("Recorded_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("recorded_at");

                    b.HasKey("Id");

                    b.HasIndex("Owner_id");

                    b.HasIndex("Property_id");

                    b.ToTable("payment_records", (string)null);
                });

            modelBuilder.Entity("PropertyWeb.Models.Property_record", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<string>("Address_line")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("address_line");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<Guid>("Owner_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<string>("Property_type")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("property_type");

                    b.Property<string>("Unit_label")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("unit_label");

                    b.HasKey("Id");

                    b.HasIndex("Owner_id");

                    b.ToTable("properties", (string)null);
                });

            modelBuilder.Entity("PropertyWeb.Models.Repair_ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<Guid?>("Assigned_user_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("assigned_user_id");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("description");

                    b.Property<string>("Image_url")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("image_url");

                    b.Property<Guid>("Owner_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("owner_id");

                    b.Property<Guid>("Property_id")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("property_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("title");

                    b.Property<DateTime?>("Updated_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("updated_at");

                    b.HasKey("Id");

                    b.HasIndex("Assigned_user_id");

                    b.HasIndex("Owner_id");

                    b.HasIndex("Property_id");

                    b.ToTable("repair_tickets", (string)null);
                });

            modelBuilder.Entity("PropertyWeb.Models.User_account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("id");

                    b.Property<DateTime>("Created_at")
                        .HasColumnType("datetime2")
                        .HasColumnName("created_at");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)")
                        .HasColumnName("email");

                    b.Property<string>("Password_hash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Phone")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("phone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasColumnName("role");

                    b.Property<string>("User_name")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)")
                        .HasColumnName("user_name");

                    b.HasKey("Id");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("PropertyWeb.Models.Payment_record", b =>
                {
                    b.HasOne("PropertyWeb.Models.User_account", "Owner")
                        .WithMany()
                        .HasForeignKey("Owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyWeb.Models.Property_record", "Property")
                        .WithMany("Payment_list")
                        .HasForeignKey("Property_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyWeb.Models.Property_record", b =>
                {
                    b.HasOne("PropertyWeb.Models.User_account", "Owner")
                        .WithMany("Property_list")
                        .HasForeignKey("Owner_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("PropertyWeb.Models.Repair_ticket", b =>
                {
                    b.HasOne("PropertyWeb.Models.User_account", "Assigned_user")
                        .WithMany("Assigned_ticket_list")
                        .HasForeignKey("Assigned_user_id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("PropertyWeb.Models.User_account", "Owner")
                        .WithMany("Submitted_ticket_list")
                        .HasForeignKey("Owner_id")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyWeb.Models.Property_record", "Property")
                        .WithMany("Ticket_list")
                        .HasForeignKey("Property_id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assigned_user");

                    b.Navigation("Owner");

                    b.Navigation("Property");
                });

            modelBuilder.Entity("PropertyWeb.Models.Property_record", b =>
                {
                    b.Navigation("Payment_list");

                    b.Navigation("Ticket_list");
                });

            modelBuilder.Entity("PropertyWeb.Models.User_account", b =>
                {
                    b.Navigation("Assigned_ticket_list");

                    b.Navigation("Property_list");

                    b.Navigation("Submitted_ticket_list");
                });
#pragma warning restore 612, 618
        }
    }
}
